# -*- coding: utf-8 -*-
"""Project_Intelligent_Fraud_Detection_Using_AI_and_Anomaly_Analytics_i.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hRjAqHM_ucq5d4tEdPesIrwkONjZ_G9k

# Intelligent Fraud Detection Using AI and Anomaly Analytics

## Understand the fraud problem context

Financial fraud is a rare but high-impact event. Traditional rule-based systems often struggle with the evolving nature of fraud.
In this demonstration, fraud detection is treated as an anomaly detection problem using an unsupervised learning approach (Isolation Forest).

**Goal**: Identify unusual transaction patterns that deviate from the norm.

## 1. Input the required libraries

*   Import the pandas library for data handling and analysis
*   Import the NumPy library for numerical computations
*   Import matplotlib’s pyplot module for data visualization
*   Import the seaborn library for statistical data visualization
*   Import the IsolationForest algorithm from sklearn for anomaly detection
*   Import LabelEncoder and StandardScaler from sklearn for categorical encoding and feature scaling
*   Import classification_report and confusion_matrix from sklearn for model performance evaluation
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

# %matplotlib inline

"""## 2. Load and explore data
Load the transaction dataset and examine its structure.

*   Define the file path of the dataset to be loaded
*   Load the CSV file into a pandas DataFrame using read_csv()
*   Display the first few rows of the DataFrame to preview the dataset



"""

file_path = '/dataset/Transaction_dataset_log.csv'
df = pd.read_csv(file_path)

# Display first few rows
df.head()

"""### Check the data information and statistics"""

print(df.info())
df.describe()

"""### Analyze fraud distribution
Fraud typically accounts for a very small percentage of total transactions (imbalanced dataset).
"""

fraud_counts = df['isFraud'].value_counts()
print(fraud_counts)

plt.figure(figsize=(6, 4))
sns.barplot(x=fraud_counts.index, y=fraud_counts.values)
plt.title('Distribution of Fraud vs. Normal Transactions')
plt.xlabel('isFraud (0: Normal, 1: Fraud)')
plt.ylabel('Count')
plt.yscale('log') # Use log scale due to high imbalance
plt.show()

"""## 3. Data cleaning
Before preprocessing, ensure data quality by checking the following:
  
* **Missing values**: Check and handle missing data

* **Outliers**: Check for extreme values

**Note:** In fraud detection, outliers might be the targets.

### Missing values
Check and handle the mising data in the dataset.
"""

missing_values = df.isnull().sum()
print(missing_values)

# If there were missing values, we'd handle them (e.g., drop or impute)
# df.dropna(inplace=True) # Example for dropping

"""### Outlier visualization
Use Boxplots to visualize the range of transaction amounts.
"""

plt.figure(figsize=(10, 4))
sns.boxplot(x=df['amount'])
plt.title('Boxplot of Transaction Amounts')
plt.show()

"""## 4. Feature engineering and preprocessing
To help the model, engineer features that capture transaction behavior logic:

**errorBalanceOrig**: Difference between the original balance change and the transaction amount

**errorBalanceDest**: Difference between the destination balance change and the transaction amount

Then, **scale** the data because the Isolation Forest is sensitive to the magnitude of values
"""

# Drop non-behavioral columns
cols_to_drop = ['nameOrig', 'nameDest', 'isFlaggedFraud']
df_processed = df.drop(columns=cols_to_drop)

# Encode 'type' column
le = LabelEncoder()
df_processed['type'] = le.fit_transform(df_processed['type'])

# Feature Engineering: Balance Errors
df_processed['errorBalanceOrig'] = df_processed['newbalanceOrig'] + df_processed['amount'] - df_processed['oldbalanceOrg']
df_processed['errorBalanceDest'] = df_processed['oldbalanceDest'] + df_processed['amount'] - df_processed['newbalanceDest']

# Preview processed data
df_processed.head()

"""## 5. Train or test split
To properly evaluate the model, split the data into a training set and a testing set.
- **Training Set**: Used to learn the normal behavior
- **Testing Set**: Used to validate if the model can detect anomalies in unseen data
"""

# Use a larger subset or full dataset if possible. Using 10% for demo speed.
sample_df = df_processed.sample(frac=0.1, random_state=42)

X = sample_df.drop(columns=['isFraud'])
y = sample_df['isFraud']

# Split into Train (80%) and Test (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Scale the features (Fit on Train, Transform on Test)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Training Data Shape: {X_train.shape}")
print(f"Testing Data Shape: {X_test.shape}")

"""## 6. Build an AI-driven anomaly detection model
Use **Isolation Forest**
- Calculate `contamination` dynamically based on the training set to tell the model approximately how many anomalies to expect.
"""

contamination_factor = y_train.value_counts(normalize=True)[1]
print(f"Dynamic Contamination Factor: {contamination_factor}")

# Initialize Isolation Forest
iso_forest = IsolationForest(n_estimators=100, contamination=contamination_factor, random_state=42, n_jobs=-1)

# Fit on Scaled Training Data
iso_forest.fit(X_train_scaled)

"""## 7. Evaluation
Evaluate the model on both the **Training Set** and the **Testing Set**.
Since Isolation Forest returns -1 for anomalies and 1 for normal, so to map these to the labels (1 for Fraud, 0 for Normal).
"""

def evaluate_model(model, X, y, set_name="Data"):
    # Predict: -1 for anomaly, 1 for normal
    y_pred = model.predict(X)

    # Map: -1 -> 1 (Fraud), 1 -> 0 (Normal)
    y_pred_mapped = [1 if x == -1 else 0 for x in y_pred]

    print(f"--- {set_name} Evaluation ---")
    print(classification_report(y, y_pred_mapped))

    return y_pred_mapped

# Evaluate on Train
y_train_pred = evaluate_model(iso_forest, X_train_scaled, y_train, set_name="Training")

# Evaluate on Test
y_test_pred = evaluate_model(iso_forest, X_test_scaled, y_test, set_name="Testing")

"""### Confusion matrix (test set)
Visualize performance on unseen data
"""

cm = confusion_matrix(y_test, y_test_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Predicted Normal', 'Predicted Fraud'], yticklabels=['Actual Normal', 'Actual Fraud'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix (Test Set)')
plt.show()

"""## 8. Visualize anomaly patterns
Display the distribution of anomaly scores for the test set
"""

# Get scores for Test set
scores_test = iso_forest.decision_function(X_test_scaled)

plt.figure(figsize=(10, 6))
# Create a temporary dataframe for plotting
test_results = X_test.copy()
test_results['isFraud'] = y_test
test_results['Anomaly_Score'] = scores_test

sns.histplot(data=test_results, x='Anomaly_Score', hue='isFraud', bins=50, kde=True, element="step", stat="density", common_norm=False)
plt.title('Distribution of Anomaly Scores (Test Set)')
plt.xlabel('Anomaly Score (Lower = More Anomalous)')
plt.show()

"""## 9. Conclusion and business impact
1. **Feature engineering** (balance errors) helped expose hidden patterns.
2. **Scaling** ensured the model treated all variance equally.
3. **Dynamic contamination** ensured the threshold was tuned to the expected rarity of fraud.


"""
